# Generated by Django 3.1.2 on 2020-10-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
